export { useBoardStore } from './stores/use-board-store'
export { useExpansionStore } from './stores/use-expansion-store'
export { useMouseAction } from './composables/use-mouse-action'
export { useEraserStore } from './stores/use-eraser-store'
export { useBoardSettingsStore, COLS_MIN, COLS_MAX, ROWS_MIN, ROWS_MAX } from './stores/use-board-settings-store'
export type { CellData, CellType, CoordsData, GraphRouteData, GraphTreeData } from './types'
export type { PathfindingAlgorithm, PathfindingFrontier } from './algorithms'
export { bfsAlgorithm, astarAlgorithm } from './algorithms'

export { default as BoardView } from './components/board-view.vue'
